### ISSUE TITLE
about proposal 

### ISSUE THREAD

**Issue by scott870430** [LiuYiwai/simple-IAM#3]
Hi!  Can you share the code of deal proposal from .mat file to .json with me?

Thanks!

**Comment by LiuYiwai** [comment]
Thanks for your reply, I also plan to reorganize this project recently.
Thank you for your participation and hope that we can exchange opinions on model implementation and model training in time.
Regarding the code of mat2json, I will upload it soon, and I will reply here again when it is finished.

**Comment by scott870430** [comment]
Sure, I look forward to your reply!

**Comment by LiuYiwai** [comment]
I have completed the upload, and the link is [here](https://github.com/LiuYiwai/MCG_mat2json).

**Comment by scott870430** [comment]
Thanks a lot! I appreciate your prompt update.
