### ISSUE TITLE
The question of test

### ISSUE THREAD

**Issue by zwy1996** [LiuYiwai/simple-IAM#4]
Hi, nice job!

When I used your code to test on voc2012 test, i met the question following. Could you give me a suggestion?
Thanks very much!

Traceback (most recent call last):
  File "main.py", line 89, in <module>
    main(args)
  File "main.py", line 74, in main
    solver.inference(data_loader)
  File "/disk4/zwy_data/wsis/simple-IAM/solver.py", line 491, in inference
    cmap=plt.cm.get_cmap())
  File "/home/harry/anaconda2/envs/siam/lib/python3.6/site-packages/matplotlib/__init__.py", line 1447, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/harry/anaconda2/envs/siam/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 5523, in imshow
    im.set_data(X)
  File "/home/harry/anaconda2/envs/siam/lib/python3.6/site-packages/matplotlib/image.py", line 698, in set_data
    self._A = cbook.safe_masked_invalid(A, copy=True)
  File "/home/harry/anaconda2/envs/siam/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 682, in safe_masked_invalid
    x = np.array(x, subok=True, copy=copy)
  File "/home/harry/anaconda2/envs/siam/lib/python3.6/site-packages/torch/tensor.py", line 449, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

My environment was following:
certifi         2020.12.5
cycler          0.10.0
Cython          0.29.22
kiwisolver      1.3.1
matplotlib      3.3.4
numpy           1.19.5
opencv-python   3.4.3.18
Pillow          8.1.0
pip             21.0.1
protobuf        3.15.1
pydensecrf      1.0rc3
pyparsing       2.4.7
python-dateutil 2.8.1
PyYAML          5.4.1
scipy           1.5.4
setuptools      49.6.0.post20210108
six             1.15.0
tensorboardX    2.1
torch           1.3.1
torchvision     0.4.2
wheel           0.36.2

**Comment by LiuYiwai** [comment]
Sorry for my late reply, have you solved this problem? I did not find this line of code
```
cmap=plt.cm.get_cmap()
```

**Comment by zwy1996** [comment]
Thanks for your response!
I thought maybe the difference of the version of matplotlib, Could you please offer your environment? Specially the version of matplotlb.

Thanks very much!

**Comment by LiuYiwai** [comment]
My environment matplotlib version is also 3.3.4, but I use my cpu environment for testing, torch version is 1.71, torchvision version is 0.8.2, I will use the GPU environment to try again in the afternoon.

**Comment by LiuYiwai** [comment]
Thank you for your attention, I have reproduced this bug, I solved it by modifying the following, you can try it.

File "solver.py", line 490
before
```
class_response_maps[it, class_idx]
```
after
```
class_response_maps[it, class_idx].cpu()
```

**Comment by zwy1996** [comment]
Thank you very much, I have no bug now.

I have a small question, which gpu card did you used, I used the 1080ti, because of the memory, I only used the bs=4, it made the train process too slowly, did the code support the mutil-gpu?

Thanks very much!

**Comment by LiuYiwai** [comment]
My GPU device is 2080Ti, I tried to use the sub_iterate_num parameter to reduce the memory usage.

At the same time, I want to say that I don't have much confidence in the implementation of this model, because the author of the paper did not provide the code and hyperparameters. If you have good suggestions, you can tell me.

**Comment by zwy1996** [comment]
Thanks very much!

I am a freshman in the wsis. Did you know how to get the mAP in the paper? Or I should find another program?

**Comment by LiuYiwai** [comment]
The original project doesn't seem to have this part, and I am a little confused about the implementation of PRM, so I haven't implemented this part.

**Comment by zwy1996** [comment]
Thank you very much！

**Comment by LiuYiwai** [comment]
I think of one thing that I hope will help you. For the VOC2012, the calculation of evaluation needs to be submitted to the [official website](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/). Because the test set does not contain GT.

Maybe you can refer to the official website to write code.

**Comment by zwy1996** [comment]
Yes, but I thought the validate set of voc2012 should have the gt. However, I did not find code that can get the mAP of WSIS.
Thank you for your nice suggestions!
